export const LOAN_STATUSES = {
  ACTIVE: 'ACTIVE',
  FINISHED: 'FINISHED',
  RENOVATED: 'RENOVATED',
  CANCELLED: 'CANCELLED',
} as const

export const PAYMENT_METHODS = {
  CASH: 'CASH',
  MONEY_TRANSFER: 'MONEY_TRANSFER',
} as const

export const TRANSACTION_TYPES = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER',
  INVESTMENT: 'INVESTMENT',
} as const
