// Income sources
export const INCOME_SOURCES = {
  CASH_LOAN_PAYMENT: 'CASH_LOAN_PAYMENT',
  BANK_LOAN_PAYMENT: 'BANK_LOAN_PAYMENT',
  BANK_INCOME: 'BANK_INCOME',
  OTHER_INCOME: 'OTHER_INCOME',
} as const

// Expense sources
export const EXPENSE_SOURCES = {
  LOAN_GRANTED: 'LOAN_GRANTED',
  LOAN_GRANTED_COMISSION: 'LOAN_GRANTED_COMISSION',
  LOAN_PAYMENT_COMISSION: 'LOAN_PAYMENT_COMISSION',
  PREPAID_GAS: 'PREPAID_GAS',
  TRAVEL_EXPENSES: 'TRAVEL_EXPENSES',
} as const
